# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: "Star Wars" }, { name: "Lord of the Rings" }])
#   Character.create(name: "Luke" movie: movies.first)
Industry.find_or_create_by(name: "Agriculture And Allied Industries")
Industry.find_or_create_by(name: "Automobiles")                                    
Industry.find_or_create_by(name: "Auto Components")                            
Industry.find_or_create_by(name: "Aviation")                                          
Industry.find_or_create_by(name: "Banking")                                           
Industry.find_or_create_by(name: "Biotechnology")                                
Industry.find_or_create_by(name: "Cement")                                           
Industry.find_or_create_by(name: "Chemicals")                                        
Industry.find_or_create_by(name: "Consumer Durables")                        
Industry.find_or_create_by(name: "Defence Manufacturing")                
Industry.find_or_create_by(name: "E Commerce")                          
Industry.find_or_create_by(name: "Education And Training")                           
Industry.find_or_create_by(name: "Electronics System Design & Manufacturing")
Industry.find_or_create_by(name: "Engineering And Capital Goods")
Industry.find_or_create_by(name: "Financial Services")
Industry.find_or_create_by(name: "FMCG")
Industry.find_or_create_by(name: "Gems And Jewellery")
Industry.find_or_create_by(name: "Healthcare")
Industry.find_or_create_by(name: "Infrastructure")
Industry.find_or_create_by(name: "Insurance")
Industry.find_or_create_by(name: "It & BPM")
Industry.find_or_create_by(name: "Manufacturing")
Industry.find_or_create_by(name: "Media And Entertainment")
Industry.find_or_create_by(name: "Medical Devices")
Industry.find_or_create_by(name: "Metals And Mining")
Industry.find_or_create_by(name: "MSME")
Industry.find_or_create_by(name: "Oil And Gas")
Industry.find_or_create_by(name: "Pharmaceuticals")
Industry.find_or_create_by(name: "Ports")
Industry.find_or_create_by(name: "Power")
Industry.find_or_create_by(name: "Railways")
Industry.find_or_create_by(name: "Real Estate")
Industry.find_or_create_by(name: "Renewable Energy")
Industry.find_or_create_by(name: "Retail")
Industry.find_or_create_by(name: "Roads")
Industry.find_or_create_by(name: "Science And Technology")
Industry.find_or_create_by(name: "Services")
Industry.find_or_create_by(name: "Steel")
Industry.find_or_create_by(name: "Telecommunications")
Industry.find_or_create_by(name: "Textiles")
Industry.find_or_create_by(name: "Tourism And Hospitality")